# .gitleaks.toml

# Ignore files that match the specified patterns
[ignore]
  paths = [
    "builds/windows/desktop/11/data/autounattend.pkrtpl.hcl",
    "builds/windows/desktop/10/data/autounattend.pkrtpl.hcl",
    "builds/windows/server/2022/data/autounattend.pkrtpl.hcl",
    "builds/windows/server/2019/data/autounattend.pkrtpl.hcl"
  ]
